image: gitpod/workspace-mysql:branch-mysql
ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
tasks:
  - init: composer --no-dev --ignore-platform-reqs install && npm i
  - name: MySQL
    command: >
      mysqld
  - name: php
    command: >
      php -S 127.0.0.1:8080
